---
abstract: 'Iterate the diamond operator via a Perl array'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Slurp: 0
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Syntax::Feature::EachOnArray: 0
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tie-Diamond
requires:
  perl: 5.010001
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Tie-Diamond
  homepage: https://metacpan.org/release/Tie-Diamond
  repository: git://github.com/sharyanto/perl-Tie-Diamond.git
version: 0.05
